FROM node:20.10.0

WORKDIR /app

# Build args - MUST be set when building for production
# Example: docker build --build-arg REACT_APP_API_URL=http://YOUR_IP:4001 ...
ARG REACT_APP_API_URL
ARG REACT_APP_API_GRAPHQL_URL
ARG REACT_APP_API_WS

ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_API_GRAPHQL_URL=$REACT_APP_API_GRAPHQL_URL
ENV REACT_APP_API_WS=$REACT_APP_API_WS

COPY . .

RUN yarn
RUN yarn build

EXPOSE 3000

CMD ["yarn", "start", "-H", "0.0.0.0"]

