services:
  booking:
    container_name: booking-next
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    networks:
      - client-network

networks:
  client-network:
    driver: bridge

